services:
  notifications-api:
    image: ${DOCKER_IMAGE_TAG}
    container_name: dotcruz-notifications-api
    restart: unless-stopped
    ports:
      - "5050:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Settings__ApiKey=${API_KEY}
      - ConnectionStrings__MongoDb=${MONGO_CONNECTION_STRING}
      - Settings__MongoDbSettings__DatabaseName=${MONGO_DATABASE_NAME}
      - Settings__AWS__Region=${AWS_REGION}
      - Settings__AWS__AccessKey=${AWS_ACCESS_KEY_ID_VPS}
      - Settings__AWS__SecretKey=${AWS_SECRET_ACCESS_KEY_VPS}
      - Settings__AWS__SqsQueueArn=${AWS_SQS_QUEUE_ARN}
      - Settings__AWS__SchedulerRoleArn=${AWS_SCHEDULER_ROLE_ARN}
      - Settings__AWS__SmtpParameterPath=${AWS_SMTP_PARAMETER_PATH}
    networks:
      - dotcruz_net
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  dotcruz_net:
    name: dotcruz_net
    external: true
