//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotCruz.Notifications.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceLogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLogMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotCruz.Notifications.CrossCutting.Resources.ResourceLogMessages", typeof(ResourceLogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Consuming notification {0}.
        /// </summary>
        public static string CONSUMING_NOTIFICATION {
            get {
                return ResourceManager.GetString("CONSUMING_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error occurred while polling scheduled notifications..
        /// </summary>
        public static string ERROR_POLLING_NOTIFICATIONS {
            get {
                return ResourceManager.GetString("ERROR_POLLING_NOTIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error sending notification {0}..
        /// </summary>
        public static string ERROR_SENDING_NOTIFICATION {
            get {
                return ResourceManager.GetString("ERROR_SENDING_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Notification {0} already sent..
        /// </summary>
        public static string NOTIFICATION_ALREADY_SENT {
            get {
                return ResourceManager.GetString("NOTIFICATION_ALREADY_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Notification {0} not found..
        /// </summary>
        public static string NOTIFICATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("NOTIFICATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ScheduledNotificationPoller started..
        /// </summary>
        public static string POLLER_STARTED {
            get {
                return ResourceManager.GetString("POLLER_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processing scheduled notification {0}.
        /// </summary>
        public static string PROCESSING_SCHEDULED_NOTIFICATION {
            get {
                return ResourceManager.GetString("PROCESSING_SCHEDULED_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sending Email to {0}: {1}.
        /// </summary>
        public static string SENDING_EMAIL {
            get {
                return ResourceManager.GetString("SENDING_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sending Push Notification to {0}: {1}.
        /// </summary>
        public static string SENDING_PUSH {
            get {
                return ResourceManager.GetString("SENDING_PUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sending SMS to {0}: {1}.
        /// </summary>
        public static string SENDING_SMS {
            get {
                return ResourceManager.GetString("SENDING_SMS", resourceCulture);
            }
        }
    }
}
